version: "3.1"

services:
  notebook:
    build:
      context: ./notebook
      dockerfile: Dockerfile
    image: deega/dask-notebook
    hostname: notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB="yes"